name: Build Hagezi NRD wildcard for Blocky

on:
  schedule:
    - cron: "0 7 * * *"   # 07:00 Europe/Madrid
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download and process NRD files
        run: |
          set -euo pipefail
          mkdir -p NRD

          SRC7="https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/domains/nrd7.txt"
          SRC14="https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/domains/nrd14-8.txt"

          # Version stamp (UTC)
          export TS="$(date -u +%Y%m%d%H%M)"

          build_file () {
            local src="$1"
            local out="$2"
            local title="$3"
            local desc="$4"

            TMPFILE="$(mktemp)"
            curl -fsSL \
              --connect-timeout 5 \
              --max-time 20 \
              --retry 2 \
              --retry-delay 1 \
              --retry-all-errors \
              "$src" -o "$TMPFILE"

            # Compute checksum and compare with previous one
            NEWSUM="$(sha256sum "$TMPFILE" | cut -d' ' -f1)"
            CHECKFILE=".checksums/$(basename "$out").sha256"
            mkdir -p .checksums

            if [ -f "$CHECKFILE" ] && grep -q "$NEWSUM" "$CHECKFILE"; then
              echo "No changes detected for $src → skipping."
              rm -f "$TMPFILE"
              return
            fi

            # Process new version
            awk '/^#/ {next} NF {gsub(/\r/,""); print "*." $0}' "$TMPFILE" \
              | sort -u > "${out}.domains"

            {
              echo "# Title: ${title}"
              echo "# Description: ${desc}"
              echo "# Homepage: https://github.com/${GITHUB_REPOSITORY}"
              echo "# License: https://github.com/${GITHUB_REPOSITORY}/blob/main/LICENSE"
              echo "# Version: ${TS}"
              echo "# Original Source: https://github.com/hagezi/dns-blocklists"
              echo "# Syntax: Domains Wildcard - Blocky (v0.23 or newer)"
              echo "#"
              cat "${out}.domains"
            } > "${out}"

            echo "$NEWSUM" > "$CHECKFILE"

            rm -f "${out}.domains" "$TMPFILE"
            echo "Wrote ${out} (lines: $(wc -l < "${out}"))"
          }

          build_file "$SRC7"  "NRD/nrd7_asterisk.txt"    "NRD 7 days (wildcard)"       "Newly Registered Domains (last 7 days)"
          build_file "$SRC14" "NRD/nrd14-8_asterisk.txt" "NRD 14->8 days (wildcard)"   "Newly Registered Domains (from day 14 to day 8)"

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(nrd): refresh wildcard lists (only if upstream changed)"
          file_pattern: "NRD/*.txt .checksums/*.sha256"
