name: Build Hagezi NRD wildcard for Blocky

on:
  schedule:
    - cron: "0 7 * * *"   # 07:00 Europe/Madrid during CEST (UTC+2)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build NRD wildcard files (wildcard-only)
        run: |
          set -euo pipefail
          mkdir -p NRD

          SRC7="https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/domains/nrd7.txt"
          SRC14="https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/domains/nrd14-8.txt"

          # Version stamp (UTC). For Madrid local time, set TZ=Europe/Madrid before date
          export TS="$(date -u +%Y%m%d%H%M)"

          # Centralize curl flags to avoid line continuation issues
          CURL="curl -fsSL --connect-timeout 5 --max-time 20 --retry 2 --retry-delay 1 --retry-all-errors"

          build_file () {
            local src="$1"
            local out="$2"
            local title="$3"
            local desc="$4"

            # 1) Extract domains -> temp file, sorted & unique
            $CURL "$src" \
            | awk '/^#/ {next} NF {gsub(/\r/,""); print "*." $0}' \
            | sort -u > "${out}.domains"

            # 2) Write header, then append domains
            {
              echo "# Title: ${title}"
              echo "# Description: ${desc}"
              echo "# Homepage: https://github.com/${GITHUB_REPOSITORY}"
              echo "# License: https://github.com/${GITHUB_REPOSITORY}/blob/main/LICENSE"
              echo "# Version: ${TS}"
              echo "# Original Source: https://github.com/hagezi/dns-blocklists"
              echo "# Syntax: Domains Wildcard - Blocky (v0.23 or newer)"
              echo "#"
              cat "${out}.domains"
            } > "${out}"

            rm -f "${out}.domains"
            echo "Wrote ${out} (lines: $(wc -l < "${out}"))"
          }

          build_file "$SRC7"  "NRD/nrd7_asterisk.txt"    "NRD 7 days (wildcard)"       "Newly Registered Domains (last 7 days) sourced from Hagezi's dns-blocklists"
          build_file "$SRC14" "NRD/nrd14-8_asterisk.txt" "NRD 14->8 days (wildcard)"   "Newly Registered Domains (from day 14 to day 8) sourced from Hagezi's dns-blocklists"

          echo "Preview 7d:"
          head -n 12 NRD/nrd7_asterisk.txt || true
          echo "Preview 14-8d:"
          head -n 12 NRD/nrd14-8_asterisk.txt || true

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(nrd): refresh wildcard lists (7d, 14-8d)"
          file_pattern: "NRD/*.txt"
